export type FallbackProduct = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  price: number;
  image: string;
  inStock: boolean;
  featured: boolean;
  category: string;
  categorySlug: string;
  shortDescription: string;
  description: string;
  specifications: { name: string; value: string; group: string }[];
  priceIsEstimate?: boolean;
};

export const fallbackCatalogue: FallbackProduct[] = [
  {
    id: "fallback-ipad-8-128",
    slug: "apple-ipad-8e-generation-128-go",
    name: "iPad 8e génération 128 Go",
    brand: "Apple",
    price: 130000,
    image: "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/i/p/ipad-2020-hero-space-wifi-select.png",
    inStock: true,
    featured: true,
    category: "Tablettes",
    categorySlug: "tablettes",
    shortDescription: "128 Go · Écran Retina 10,2 pouces · Clavier Logitech et accessoires offerts",
    description: "iPad 8e génération avec 128 Go de stockage, accompagné d’un clavier Logitech, d’une vitre de protection et d’une pochette. Adapté aux études, au travail, aux cours, à la bureautique, aux vidéos et à la navigation. Appareil annoncé comme d’origine, avec facture et service après-vente.",
    specifications: [
      { name: "Stockage", value: "128 Go", group: "Configuration" },
      { name: "Écran", value: "Retina 10,2 pouces", group: "Affichage" },
      { name: "Accessoires", value: "Clavier Logitech, vitre de protection et pochette", group: "Inclus" },
    ],
  },
  {
    id: "fallback-dell-precision-7760",
    slug: "dell-precision-7760-i7-16-go-512-go-rtx-a3000",
    name: "Precision 7760",
    brand: "Dell",
    price: 650000,
    priceIsEstimate: true,
    image: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/workstations/mobile-workstations/precision/17-7760/slices/laptop-precision-7760-pdp-gallery-504x350.jpg?fmt=jpg&hei=400&wid=570",
    inStock: true,
    featured: true,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i7 11e génération · 16 Go RAM · SSD 512 Go · RTX A3000 6 Go",
    description: "Station de travail Dell Precision 7760 équipée d’un Intel Core i7-11850H de 11e génération, de 16 Go de RAM DDR4 et d’un SSD NVMe de 512 Go. La carte graphique professionnelle NVIDIA RTX A3000 dispose de 6 Go de mémoire dédiée. Écran 17 pouces Full HD. Convient à l’architecture, au génie civil, à l’infographie, au montage vidéo et au développement.",
    specifications: [
      { name: "Processeur", value: "Intel Core i7-11850H, 11e génération", group: "Performance" },
      { name: "Mémoire", value: "16 Go DDR4, extensible jusqu’à 128 Go", group: "Performance" },
      { name: "Stockage", value: "SSD M.2 NVMe 512 Go", group: "Stockage" },
      { name: "Graphique", value: "NVIDIA RTX A3000, 6 Go GDDR6", group: "Affichage" },
      { name: "Écran", value: "17 pouces Full HD, 1920 × 1080", group: "Affichage" },
      { name: "Système", value: "Windows Professionnel 64 bits", group: "Logiciel" },
    ],
  },
  {
    id: "fallback-lenovo-yoga-7-16ahp9",
    slug: "lenovo-yoga-7-16ahp9-ryzen-7-16-go-512-go",
    name: "Yoga 7 16AHP9",
    brand: "Lenovo",
    price: 650000,
    priceIsEstimate: true,
    image: "https://www.notebookcheck.com/uploads/tx_nbc2/Lenovo_Yoga_7_16AHP9__1_.JPG",
    inStock: true,
    featured: true,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Ryzen 7 8840HS · 16 Go LPDDR5x · SSD 512 Go · Écran tactile convertible",
    description: "Lenovo Yoga 7 16AHP9 convertible avec processeur AMD Ryzen 7 8840HS, 16 Go de mémoire LPDDR5x et SSD NVMe de 512 Go. La partie graphique Radeon 780M est intégrée au processeur. Écran tactile 16 pouces et charnière convertible. Garantie annoncée de 12 mois.",
    specifications: [
      { name: "Processeur", value: "AMD Ryzen 7 8840HS, 8 cœurs et 16 threads", group: "Performance" },
      { name: "Mémoire", value: "16 Go LPDDR5x, 6400 MT/s", group: "Performance" },
      { name: "Stockage", value: "SSD NVMe 512 Go", group: "Stockage" },
      { name: "Graphique", value: "AMD Radeon 780M intégrée", group: "Affichage" },
      { name: "Écran", value: "Tactile 16 pouces WUXGA", group: "Affichage" },
      { name: "Garantie", value: "12 mois annoncés", group: "Services" },
    ],
  },
  {
    id: "fallback-macbook-pro-14-m1-pro-2021",
    slug: "apple-macbook-pro-14-2021-m1-pro-16-go-512-go",
    name: "MacBook Pro 14 pouces (2021)",
    brand: "Apple",
    price: 625000,
    image: "https://cdsassets.apple.com/live/7WUAS350/images/tech-specs/111902_mbp14-silver2.png",
    inStock: true,
    featured: true,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Puce M1 Pro · 16 Go mémoire unifiée · SSD 512 Go · Écran Liquid Retina XDR",
    description: "MacBook Pro 14 pouces de 2021 équipé de la puce Apple M1 Pro, avec CPU 8 cœurs et GPU 14 cœurs, 16 Go de mémoire unifiée et SSD de 512 Go. Son écran Liquid Retina XDR de 14,2 pouces prend en charge ProMotion jusqu’à 120 Hz.",
    specifications: [
      { name: "Année", value: "2021", group: "Configuration" },
      { name: "Puce", value: "Apple M1 Pro, CPU 8 cœurs et GPU 14 cœurs", group: "Performance" },
      { name: "Mémoire", value: "16 Go unifiée", group: "Performance" },
      { name: "Stockage", value: "SSD 512 Go", group: "Stockage" },
      { name: "Écran", value: "14,2 pouces Liquid Retina XDR, 3024 × 1964, ProMotion 120 Hz", group: "Affichage" },
      { name: "Connectique", value: "MagSafe 3, 3 Thunderbolt 4, HDMI, SDXC", group: "Connectique" },
    ],
  },
  {
    id: "fallback-thinkpad-x1-carbon-gen-8",
    slug: "lenovo-thinkpad-x1-carbon-gen-8-i7-16-go-256-go-tactile",
    name: "ThinkPad X1 Carbon Gen 8 tactile",
    brand: "Lenovo",
    price: 250000,
    priceIsEstimate: true,
    image: "https://gfx3.senetic.com/akeneo-catalog/e/6/2/c/e62caec4dc57a9e6667efdf9e30c43c0defd8715_1699953_20U9004MMX_image1.jpg",
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i7 10e génération · 16 Go RAM · SSD NVMe 256 Go · Écran tactile",
    description: "Ultrabook Lenovo ThinkPad X1 Carbon Gen 8 avec Intel Core i7 de 10e génération, 16 Go de RAM, SSD NVMe de 256 Go et écran tactile Full HD de 14 pouces. Châssis léger en fibre de carbone, clavier rétroéclairé, lecteur d’empreintes et chargeur USB-C d’origine annoncés. État annoncé : 10/10.",
    specifications: [
      { name: "Processeur", value: "Intel Core i7, 10e génération", group: "Performance" },
      { name: "Mémoire", value: "16 Go", group: "Performance" },
      { name: "Stockage", value: "SSD NVMe 256 Go", group: "Stockage" },
      { name: "Écran", value: "14 pouces Full HD tactile, IPS, 400 nits", group: "Affichage" },
      { name: "Poids", value: "Environ 1,09 kg", group: "Conception" },
      { name: "Autonomie", value: "10 à 12 heures annoncées", group: "Batterie" },
    ],
  },
  {
    id: "fallback-hp-probook-650-g4",
    slug: "hp-probook-650-g4-i5-8-go-128-go-500-go",
    name: "ProBook 650 G4",
    brand: "HP",
    price: 190000,
    priceIsEstimate: true,
    image: "https://media.ldlc.com/r1600/mktp/product/productImage/230531/50/6e31516d69ab4d29bf5220e757be409b.webp",
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i5 8e génération · 8 Go RAM · SSD 128 Go + disque 500 Go",
    description: "HP ProBook 650 G4 de 15,6 pouces équipé d’un Intel Core i5 de 8e génération, de 8 Go de RAM, d’un SSD de 128 Go et d’un disque dur SATA de 500 Go. Connectivité annoncée : Wi-Fi, Bluetooth, Ethernet, USB 3.0 et USB-C. Batterie annoncée en excellent état et Windows 11 Pro.",
    specifications: [
      { name: "Processeur", value: "Intel Core i5, 8e génération", group: "Performance" },
      { name: "Mémoire", value: "8 Go RAM", group: "Performance" },
      { name: "Stockage", value: "SSD 128 Go + disque SATA 500 Go", group: "Stockage" },
      { name: "Écran", value: "15,6 pouces", group: "Affichage" },
      { name: "Système", value: "Windows 11 Pro", group: "Logiciel" },
    ],
  },
  {
    id: "fallback-asus-rog-zephyrus-s-gx531gs",
    slug: "asus-rog-zephyrus-s-gx531gs-i7-16-go-rtx-1070",
    name: "ROG Zephyrus S GX531GS",
    brand: "Asus",
    price: 480000,
    image: "https://www.notebookcheck.net/uploads/tx_nbc2/ASUSZephyrusS-GX531GX__1_.JPG",
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i7 8e génération · 16 Go RAM · GTX 1070 8 Go · SSD 256 Go + HDD 1 To",
    description: "Ordinateur gaming ASUS ROG Zephyrus S GX531GS avec Intel Core i7 de 8e génération, 16 Go de RAM DDR4, SSD de 256 Go et disque dur de 1 To. Carte graphique NVIDIA GeForce GTX 1070 avec 8 Go dédiés et écran Full HD de 15,6 pouces. Adapté au jeu, au montage vidéo, à la 3D et aux logiciels professionnels.",
    specifications: [
      { name: "Processeur", value: "Intel Core i7, 8e génération, 6 cœurs et 12 threads", group: "Performance" },
      { name: "Mémoire", value: "16 Go DDR4", group: "Performance" },
      { name: "Stockage", value: "SSD 256 Go + HDD 1 To", group: "Stockage" },
      { name: "Graphique", value: "NVIDIA GeForce GTX 1070, 8 Go dédiés", group: "Affichage" },
      { name: "Écran", value: "15,6 pouces Full HD", group: "Affichage" },
    ],
  },
  {
    id: "fallback-hp-probook-x360-g2",
    slug: "hp-probook-x360-g2-tactile-4-go-192-go",
    name: "ProBook x360 G2",
    brand: "HP",
    price: 120000,
    priceIsEstimate: true,
    image: "https://jp.ext.hp.com/content/dam/jp-ext-hp-com/jp/ja/ec/notebooks/business/pro_x360_ee_g2/images/move_full.jpg",
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Quad-core · 4 Go DDR4 · SSD 192 Go · Écran tactile convertible 360°",
    description: "HP ProBook x360 G2 convertible avec écran tactile rotatif à 360 degrés, 4 Go de RAM DDR4 et SSD de 192 Go. La configuration communiquée indique un processeur quad-core à 2,3 GHz, une webcam, Bluetooth et une autonomie annoncée de plus de six heures.",
    specifications: [
      { name: "Processeur", value: "Intel quad-core, 2,3 GHz annoncés", group: "Performance" },
      { name: "Mémoire", value: "4 Go DDR4", group: "Performance" },
      { name: "Stockage", value: "SSD 192 Go", group: "Stockage" },
      { name: "Écran", value: "Tactile convertible à 360°, environ 12 pouces annoncés", group: "Affichage" },
      { name: "Connectique", value: "USB-C, HDMI, Bluetooth et webcam", group: "Connectique" },
    ],
  },
  {
    id: "fallback-macbook-pro-14-m4-pro-2024",
    slug: "apple-macbook-pro-14-2024-m4-pro-24-go-512-go",
    name: "MacBook Pro 14 pouces M4 Pro (2024)",
    brand: "Apple",
    price: 1600000,
    priceIsEstimate: true,
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MP_150954591/fee_786_587_png",
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Puce M4 Pro · CPU 12 cœurs · GPU 16 cœurs · 24 Go RAM · SSD 512 Go",
    description: "MacBook Pro 14 pouces de 2024 avec puce Apple M4 Pro, CPU 12 cœurs, GPU 16 cœurs, 24 Go de mémoire unifiée et SSD de 512 Go. Écran Liquid Retina XDR avec ProMotion jusqu’à 120 Hz, connectique Thunderbolt 5 et macOS Sequoia.",
    specifications: [
      { name: "Puce", value: "Apple M4 Pro, CPU 12 cœurs et GPU 16 cœurs", group: "Performance" },
      { name: "Neural Engine", value: "16 cœurs", group: "Performance" },
      { name: "Mémoire", value: "24 Go unifiée", group: "Performance" },
      { name: "Stockage", value: "SSD 512 Go", group: "Stockage" },
      { name: "Écran", value: "14,2 pouces Liquid Retina XDR, ProMotion 120 Hz", group: "Affichage" },
      { name: "Connectique", value: "Thunderbolt 5, USB-C, HDMI, MagSafe 3 et SDXC", group: "Connectique" },
      { name: "Système", value: "macOS Sequoia", group: "Logiciel" },
    ],
  },
  {
    id: "fallback-dell-latitude-3300",
    slug: "dell-latitude-3300-i5-8-go-256-go",
    name: "Latitude 3300",
    brand: "Dell",
    price: 180000,
    priceIsEstimate: true,
    image: "https://www.multivu.com/players/English/8356753-dell-technologies-bett-education/image/Latitude3300_1548180874597-HR.jpg",
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i5 8e génération · 8 Go DDR4 · SSD 256 Go · Écran 13,3 pouces",
    description: "Dell Latitude 3300 compact avec Intel Core i5 de 8e génération, 8 Go de RAM DDR4 et SSD de 256 Go. Écran de 13,3 pouces, webcam intégrée, Wi-Fi, HDMI, USB-C et autonomie annoncée d’environ quatre heures.",
    specifications: [
      { name: "Processeur", value: "Intel Core i5, 8e génération", group: "Performance" },
      { name: "Mémoire", value: "8 Go DDR4", group: "Performance" },
      { name: "Stockage", value: "SSD 256 Go", group: "Stockage" },
      { name: "Écran", value: "13,3 pouces", group: "Affichage" },
      { name: "Connectique", value: "Wi-Fi, HDMI, USB-C, USB et webcam", group: "Connectique" },
      { name: "Autonomie", value: "Environ 4 heures annoncées", group: "Batterie" },
    ],
  },
  {
    id: "fallback-macbook-pro-16-m2-pro-2023",
    slug: "apple-macbook-pro-16-2023-m2-pro-32-go-1-to",
    name: "MacBook Pro 16 pouces M2 Pro (2023)",
    brand: "Apple",
    price: 1350000,
    image: "https://images.stockx.com/images/Apple-Macbook-Pro-16-M2-Pro-12-Core-CPU-38-Core-GPU-32GB-RAM-1TB-SSD-2023-Model-MNWA3LL-A-Space-Gray.jpg?auto=compress&bg=FFFFFF&dpr=2&fit=fill&fm=webp&h=500&q=90&trim=color&updated_at=1675359314&w=700",
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Puce M2 Pro · 32 Go mémoire unifiée · SSD 1 To · Écran Liquid Retina XDR 16,2 pouces",
    description: "MacBook Pro 16 pouces de 2023 équipé de la puce Apple M2 Pro, avec 32 Go de mémoire unifiée et SSD de 1 To. Écran Liquid Retina XDR de 16,2 pouces, Wi-Fi 6E, Bluetooth 5.3, Touch ID et connectique Thunderbolt 4, HDMI, MagSafe 3 et SDXC.",
    specifications: [
      { name: "Année", value: "2023", group: "Configuration" },
      { name: "Puce", value: "Apple M2 Pro", group: "Performance" },
      { name: "Mémoire", value: "32 Go unifiée", group: "Performance" },
      { name: "Stockage", value: "SSD 1 To", group: "Stockage" },
      { name: "Écran", value: "16,2 pouces Liquid Retina XDR, 3456 × 2234", group: "Affichage" },
      { name: "Connectique", value: "3 Thunderbolt 4, HDMI, MagSafe 3, SDXC et prise casque", group: "Connectique" },
      { name: "Réseau", value: "Wi-Fi 6E et Bluetooth 5.3", group: "Connectique" },
      { name: "Accessoires annoncés", value: "Facture, garantie, 12 mois de SAV, housse et souris sans fil", group: "Services" },
    ],
  },
];

export function getFallbackProducts(options: { categorySlug?: string; featured?: boolean; take?: number } = {}) {
  const products = fallbackCatalogue.filter((product) =>
    (!options.categorySlug || product.categorySlug === options.categorySlug) &&
    (!options.featured || product.featured),
  );
  return options.take ? products.slice(0, options.take) : products;
}

export function getFallbackProductBySlug(slug: string) {
  const product = fallbackCatalogue.find((item) => item.slug === slug);
  if (!product) return null;
  return {
    ...product,
    stockQuantity: 1,
    sku: "",
    images: [product.image],
  };
}
