export type FallbackProduct = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  price: number;
  image: string;
  galleryImages?: string[];
  inStock: boolean;
  featured: boolean;
  category: string;
  categorySlug: string;
  shortDescription: string;
  description: string;
  specifications: { name: string; value: string; group: string }[];
  priceIsEstimate?: boolean;
};

export const fallbackCatalogue: FallbackProduct[] = [
  {
    id: "fallback-ipad-8-128",
    slug: "apple-ipad-8e-generation-128-go",
    name: "iPad 8e génération 128 Go",
    brand: "Apple",
    price: 130000,
    image: "https://www.paklap.pk/media/catalog/product/cache/2cc443e44e97595ea39006016c876eaa/i/p/ipad-2020-hero-space-wifi-select.png",
    galleryImages: [
      "https://i5.walmartimages.com/asr/29c3c351-6ae5-4dad-9654-d17be78de39f.e2f9ac8a776e1e3b02aa992106b30236.jpeg?odnBg=FFFFFF&odnHeight=612&odnWidth=612",
      "https://i.ebayimg.com/images/g/vDUAAeSwmTZpIGoQ/s-l500.jpg",
      "https://www.pc-koubou.jp/upload/save_image/used/SELLMORE/2350006078588-20964.jpg",
      "https://www.voke.shop/on/demandware.static/-/Sites-storefront-voke/default/dwc7510055/tablet-apple/iPad%20A2429%202.jpg",
      "https://thumbnail.image.rakuten.co.jp/%400_mall/pc-eco2000/cabinet/ipad8.jpg",
    ],
    inStock: true,
    featured: true,
    category: "Tablettes",
    categorySlug: "tablettes",
    shortDescription: "128 Go · Écran Retina 10,2 pouces · Clavier Logitech et accessoires offerts",
    description: "iPad 8e génération avec 128 Go de stockage, accompagné d’un clavier Logitech, d’une vitre de protection et d’une pochette. Adapté aux études, au travail, aux cours, à la bureautique, aux vidéos et à la navigation. Appareil annoncé comme d’origine, avec facture et service après-vente.",
    specifications: [
      { name: "Stockage", value: "128 Go", group: "Configuration" },
      { name: "Écran", value: "Retina 10,2 pouces", group: "Affichage" },
      { name: "Accessoires", value: "Clavier Logitech, vitre de protection et pochette", group: "Inclus" },
    ],
  },
  {
    id: "fallback-dell-precision-7760",
    slug: "dell-precision-7760-i7-16-go-512-go-rtx-a3000",
    name: "Precision 7760",
    brand: "Dell",
    price: 650000,
    priceIsEstimate: true,
    image: "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/workstations/mobile-workstations/precision/17-7760/slices/laptop-precision-7760-pdp-gallery-504x350.jpg?fmt=jpg&hei=400&wid=570",
    galleryImages: [
      "https://amso.pl/hpeciai/62c669f13ff3f36fd2df00ffec4a5a6d/pol_pl_Dell-Precision-7760-i7-11800H-32GB-1TB-SSD-1920x1080-Nvidia-RTX-A3000-QWERTY-PL-Klasa-A-Windows-11-Professional-298336_4.jpg",
      "https://maytinhgiare.vn/hinh-anh/san-pham/Dell%20Precision%207760%203.jpg",
      "https://slaskiecentrumkomputerowe.pl/environment/cache/images/productGfx_482328_750_750/Dell-Precision-7760-obudowa.webp",
      "https://targetstoreg.com/cdn/shop/files/Dell_Precision_7760_mobile_workstation_17.3-inch_laptop_with_NVIDIA_RTX_A3000_graphics_TARGET_Store_Egypt_Right_Side_View.webp?v=1777827184&width=1946",
      "https://www.comtrade.pl/hpeciai/29b38a57150fa9cdf2746b043a404fba/pol_pl_Dell-Precision-7760-Core-i7-11850H-11-gen-2-5-GHz-16-GB-2-TB-SSD-17-3-FullHD-Win-11-Pro-RTX-A5000-46108_6.jpg",
    ],
    inStock: true,
    featured: true,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i7 11e génération · 16 Go RAM · SSD 512 Go · RTX A3000 6 Go",
    description: "Station de travail Dell Precision 7760 équipée d’un Intel Core i7-11850H de 11e génération, de 16 Go de RAM DDR4 et d’un SSD NVMe de 512 Go. La carte graphique professionnelle NVIDIA RTX A3000 dispose de 6 Go de mémoire dédiée. Écran 17 pouces Full HD. Convient à l’architecture, au génie civil, à l’infographie, au montage vidéo et au développement.",
    specifications: [
      { name: "Processeur", value: "Intel Core i7-11850H, 11e génération", group: "Performance" },
      { name: "Mémoire", value: "16 Go DDR4, extensible jusqu’à 128 Go", group: "Performance" },
      { name: "Stockage", value: "SSD M.2 NVMe 512 Go", group: "Stockage" },
      { name: "Graphique", value: "NVIDIA RTX A3000, 6 Go GDDR6", group: "Affichage" },
      { name: "Écran", value: "17 pouces Full HD, 1920 × 1080", group: "Affichage" },
      { name: "Système", value: "Windows Professionnel 64 bits", group: "Logiciel" },
    ],
  },
  {
    id: "fallback-lenovo-yoga-7-16ahp9",
    slug: "lenovo-yoga-7-16ahp9-ryzen-7-16-go-512-go",
    name: "Yoga 7 16AHP9",
    brand: "Lenovo",
    price: 650000,
    priceIsEstimate: true,
    image: "https://www.notebookcheck.com/uploads/tx_nbc2/Lenovo_Yoga_7_16AHP9__1_.JPG",
    galleryImages: [
      "https://hgbenin.com/media/products/1008565152.jpg",
      "https://hgbenin.com/media/products/1008565151.jpg",
      "https://hgbenin.com/media/products/1008565140.jpg",
      "https://hgbenin.com/media/products/1008565216.jpg",
      "https://hgbenin.com/media/products/1008565208.jpg",
    ],
    inStock: true,
    featured: true,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Ryzen 7 8840HS · 16 Go LPDDR5x · SSD 512 Go · Écran tactile convertible",
    description: "Lenovo Yoga 7 16AHP9 convertible avec processeur AMD Ryzen 7 8840HS, 16 Go de mémoire LPDDR5x et SSD NVMe de 512 Go. La partie graphique Radeon 780M est intégrée au processeur. Écran tactile 16 pouces et charnière convertible. Garantie annoncée de 12 mois.",
    specifications: [
      { name: "Processeur", value: "AMD Ryzen 7 8840HS, 8 cœurs et 16 threads", group: "Performance" },
      { name: "Mémoire", value: "16 Go LPDDR5x, 6400 MT/s", group: "Performance" },
      { name: "Stockage", value: "SSD NVMe 512 Go", group: "Stockage" },
      { name: "Graphique", value: "AMD Radeon 780M intégrée", group: "Affichage" },
      { name: "Écran", value: "Tactile 16 pouces WUXGA", group: "Affichage" },
      { name: "Garantie", value: "12 mois annoncés", group: "Services" },
    ],
  },
  {
    id: "fallback-macbook-pro-14-m1-pro-2021",
    slug: "apple-macbook-pro-14-2021-m1-pro-16-go-512-go",
    name: "MacBook Pro 14 pouces (2021)",
    brand: "Apple",
    price: 625000,
    image: "https://cdsassets.apple.com/live/7WUAS350/images/tech-specs/111902_mbp14-silver2.png",
    galleryImages: [
      "https://kenovo.it/media/catalog/product/cache/8a75fd9c6038609f8bbd7fccc83b971e/A/p/AppleMacbookProA2442Silver03.jpg",
      "https://www.okamac.com/90193-product_zoom_default/macbook-pro-14-2021-m1-pro-chip-apple-gpu-16-8-nucleos-32-gb-ram-32-ghz.jpg",
      "https://cdn.almostnew.de/media/71/80/80/1752157694/photoroom-003-20250710-161623.jpeg?ts=1752160324",
      "https://s3ng.cashify.in/cashify/store/product/127c0914296d492bac49a53bd3f300a0.png",
      "https://cdn.comparez-malin.fr/img/apple/2021/27817/apple-macbook-pro-14-2021-5.jpg",
    ],
    inStock: true,
    featured: true,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Puce M1 Pro · 16 Go mémoire unifiée · SSD 512 Go · Écran Liquid Retina XDR",
    description: "MacBook Pro 14 pouces de 2021 équipé de la puce Apple M1 Pro, avec CPU 8 cœurs et GPU 14 cœurs, 16 Go de mémoire unifiée et SSD de 512 Go. Son écran Liquid Retina XDR de 14,2 pouces prend en charge ProMotion jusqu’à 120 Hz.",
    specifications: [
      { name: "Année", value: "2021", group: "Configuration" },
      { name: "Puce", value: "Apple M1 Pro, CPU 8 cœurs et GPU 14 cœurs", group: "Performance" },
      { name: "Mémoire", value: "16 Go unifiée", group: "Performance" },
      { name: "Stockage", value: "SSD 512 Go", group: "Stockage" },
      { name: "Écran", value: "14,2 pouces Liquid Retina XDR, 3024 × 1964, ProMotion 120 Hz", group: "Affichage" },
      { name: "Connectique", value: "MagSafe 3, 3 Thunderbolt 4, HDMI, SDXC", group: "Connectique" },
    ],
  },
  {
    id: "fallback-thinkpad-x1-carbon-gen-8",
    slug: "lenovo-thinkpad-x1-carbon-gen-8-i7-16-go-256-go-tactile",
    name: "ThinkPad X1 Carbon Gen 8 tactile",
    brand: "Lenovo",
    price: 250000,
    priceIsEstimate: true,
    image: "https://gfx3.senetic.com/akeneo-catalog/e/6/2/c/e62caec4dc57a9e6667efdf9e30c43c0defd8715_1699953_20U9004MMX_image1.jpg",
    galleryImages: [
      "https://assets.kogan.com/images/laptopexpert/LTE-46950683246729/4-1c55703d49-4_fcd0289b-2784-4f6a-a64d-d846d6db8adc.png?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200",
      "https://cdn.cs.1worldsync.com/f2/1e/f21eef63-9dac-4854-bc6b-7e80abc2e775.jpg",
      "https://down-id.img.susercontent.com/file/id-11134207-7r991-lzsvtsqjsnu559",
      "https://www.laptopfactory.pl/userdata/public/gfx/57406/Lenovo-ThinkPad-X1-Carbon-Gen-8%2C-i7-10610U--lekki%2C-elegancki-laptop-biznesowy-z-klawiatura-US-PL-QWERTY%2C-idealny-do-pracy-w-biurze-i-w-podrozy-6.jpg",
      "https://cmsassets.public.gr/new-photos/October21/MRK2252096-laptop-lenovo-thinkpad-x1-carbon-gen-8-intel-core-i7-10510u16gb1tb-ssdintel-uhd-graphics4.png",
    ],
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i7 10e génération · 16 Go RAM · SSD NVMe 256 Go · Écran tactile",
    description: "Ultrabook Lenovo ThinkPad X1 Carbon Gen 8 avec Intel Core i7 de 10e génération, 16 Go de RAM, SSD NVMe de 256 Go et écran tactile Full HD de 14 pouces. Châssis léger en fibre de carbone, clavier rétroéclairé, lecteur d’empreintes et chargeur USB-C d’origine annoncés. État annoncé : 10/10.",
    specifications: [
      { name: "Processeur", value: "Intel Core i7, 10e génération", group: "Performance" },
      { name: "Mémoire", value: "16 Go", group: "Performance" },
      { name: "Stockage", value: "SSD NVMe 256 Go", group: "Stockage" },
      { name: "Écran", value: "14 pouces Full HD tactile, IPS, 400 nits", group: "Affichage" },
      { name: "Poids", value: "Environ 1,09 kg", group: "Conception" },
      { name: "Autonomie", value: "10 à 12 heures annoncées", group: "Batterie" },
    ],
  },
  {
    id: "fallback-hp-probook-650-g4",
    slug: "hp-probook-650-g4-i5-8-go-128-go-500-go",
    name: "ProBook 650 G4",
    brand: "HP",
    price: 190000,
    priceIsEstimate: true,
    image: "https://media.ldlc.com/r1600/mktp/product/productImage/230531/50/6e31516d69ab4d29bf5220e757be409b.webp",
    galleryImages: [
      "https://i.ebayimg.com/images/g/Uv4AAOSwSWNj5rp8/s-l1200.png",
      "https://laptopmall.pk/storage/media/jKCaxlKjlLaqaXZRAttwzVM5ftSi1fIeGkvxUhmy.jpg",
      "https://shoplet.pl/352350-thickbox_default/laptop-hp-probook-650-g4-i5-8250u-16gb-256gb-ssd-full-hd-win10pro-5905902024213.jpg",
      "https://king-tech-eg.com/cdn/shop/files/laptop-hp-probook-650-g5-3_f2683ee7-6ac6-4c4c-b96e-5f8510e6f61a.jpg?v=1740239460",
      "https://recorder.sk/image/cache/catalog/oc_6263459675dc6f2b37c9cf6445f25c910d20ca-1000x1000.jpg",
    ],
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i5 8e génération · 8 Go RAM · SSD 128 Go + disque 500 Go",
    description: "HP ProBook 650 G4 de 15,6 pouces équipé d’un Intel Core i5 de 8e génération, de 8 Go de RAM, d’un SSD de 128 Go et d’un disque dur SATA de 500 Go. Connectivité annoncée : Wi-Fi, Bluetooth, Ethernet, USB 3.0 et USB-C. Batterie annoncée en excellent état et Windows 11 Pro.",
    specifications: [
      { name: "Processeur", value: "Intel Core i5, 8e génération", group: "Performance" },
      { name: "Mémoire", value: "8 Go RAM", group: "Performance" },
      { name: "Stockage", value: "SSD 128 Go + disque SATA 500 Go", group: "Stockage" },
      { name: "Écran", value: "15,6 pouces", group: "Affichage" },
      { name: "Système", value: "Windows 11 Pro", group: "Logiciel" },
    ],
  },
  {
    id: "fallback-asus-rog-zephyrus-s-gx531gs",
    slug: "asus-rog-zephyrus-s-gx531gs-i7-16-go-rtx-1070",
    name: "ROG Zephyrus S GX531GS",
    brand: "Asus",
    price: 480000,
    image: "https://www.notebookcheck.net/uploads/tx_nbc2/ASUSZephyrusS-GX531GX__1_.JPG",
    galleryImages: [
      "https://www.adorama.com/images/Large/ASGX531GXB76_1.jpg",
      "https://www.adorama.com/images/Large/ASGX531GXB76_2.jpg",
      "https://www.adorama.com/images/Large/ASGX531GXB76_3.jpg",
      "https://www.adorama.com/images/Large/ASGX531GXB76_4.jpg",
      "https://www.adorama.com/images/Large/ASGX531GXB76_5.jpg",
    ],
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i7 8e génération · 16 Go RAM · GTX 1070 8 Go · SSD 256 Go + HDD 1 To",
    description: "Ordinateur gaming ASUS ROG Zephyrus S GX531GS avec Intel Core i7 de 8e génération, 16 Go de RAM DDR4, SSD de 256 Go et disque dur de 1 To. Carte graphique NVIDIA GeForce GTX 1070 avec 8 Go dédiés et écran Full HD de 15,6 pouces. Adapté au jeu, au montage vidéo, à la 3D et aux logiciels professionnels.",
    specifications: [
      { name: "Processeur", value: "Intel Core i7, 8e génération, 6 cœurs et 12 threads", group: "Performance" },
      { name: "Mémoire", value: "16 Go DDR4", group: "Performance" },
      { name: "Stockage", value: "SSD 256 Go + HDD 1 To", group: "Stockage" },
      { name: "Graphique", value: "NVIDIA GeForce GTX 1070, 8 Go dédiés", group: "Affichage" },
      { name: "Écran", value: "15,6 pouces Full HD", group: "Affichage" },
    ],
  },
  {
    id: "fallback-hp-probook-x360-g2",
    slug: "hp-probook-x360-g2-tactile-4-go-192-go",
    name: "ProBook x360 G2",
    brand: "HP",
    price: 120000,
    priceIsEstimate: true,
    image: "https://jp.ext.hp.com/content/dam/jp-ext-hp-com/jp/ja/ec/notebooks/business/pro_x360_ee_g2/images/move_full.jpg",
    galleryImages: [
      "https://jp.ext.hp.com/content/dam/jp-ext-hp-com/jp/ja/ec/notebooks/business/pro_x360_ee_g2/images/m/img_chara1_1.jpg",
      "https://jp.ext.hp.com/content/dam/jp-ext-hp-com/jp/ja/ec/notebooks/business/pro_x360_ee_g2/images/m/img_chara1_2.jpg",
      "https://jp.ext.hp.com/content/dam/jp-ext-hp-com/jp/ja/ec/notebooks/business/pro_x360_ee_g2/images/m/img_chara2_1.jpg",
      "https://jp.ext.hp.com/content/dam/jp-ext-hp-com/jp/ja/ec/notebooks/business/pro_x360_ee_g2/images/m/img_chara2_2.jpg",
      "https://jp.ext.hp.com/content/dam/jp-ext-hp-com/jp/ja/ec/notebooks/business/pro_x360_ee_g2/images/m/img_chara2_3.jpg",
    ],
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Quad-core · 4 Go DDR4 · SSD 192 Go · Écran tactile convertible 360°",
    description: "HP ProBook x360 G2 convertible avec écran tactile rotatif à 360 degrés, 4 Go de RAM DDR4 et SSD de 192 Go. La configuration communiquée indique un processeur quad-core à 2,3 GHz, une webcam, Bluetooth et une autonomie annoncée de plus de six heures.",
    specifications: [
      { name: "Processeur", value: "Intel quad-core, 2,3 GHz annoncés", group: "Performance" },
      { name: "Mémoire", value: "4 Go DDR4", group: "Performance" },
      { name: "Stockage", value: "SSD 192 Go", group: "Stockage" },
      { name: "Écran", value: "Tactile convertible à 360°, environ 12 pouces annoncés", group: "Affichage" },
      { name: "Connectique", value: "USB-C, HDMI, Bluetooth et webcam", group: "Connectique" },
    ],
  },
  {
    id: "fallback-macbook-pro-14-m4-pro-2024",
    slug: "apple-macbook-pro-14-2024-m4-pro-24-go-512-go",
    name: "MacBook Pro 14 pouces M4 Pro (2024)",
    brand: "Apple",
    price: 1600000,
    priceIsEstimate: true,
    image: "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MP_150954591/fee_786_587_png",
    galleryImages: [
      "https://24hstore.vn/upload_images/images/2025/01/25/macbook-pro-14-inch-2024-m4-pro-12-cpu-16-gpu-24gb-512gb-1.jpg",
      "https://24hstore.vn/upload_images/images/2025/01/25/macbook-pro-14-inch-2024-m4-pro-12-cpu-16-gpu-24gb-512gb-3.jpg",
      "https://24hstore.vn/upload_images/images/2025/01/25/macbook-pro-14-inch-2024-m4-pro-12-cpu-16-gpu-24gb-512gb-5.jpg",
      "https://persianapple.ir/UpImage/de44c87d-0c55-4d90-83a1-7dcd7f50d933.jpg",
      "https://i-shop.ru/upload/cssinliner_webp/medialibrary/64c/zifitpge0bkm45tbz7aej4eql9vr9407.webp",
    ],
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Puce M4 Pro · CPU 12 cœurs · GPU 16 cœurs · 24 Go RAM · SSD 512 Go",
    description: "MacBook Pro 14 pouces de 2024 avec puce Apple M4 Pro, CPU 12 cœurs, GPU 16 cœurs, 24 Go de mémoire unifiée et SSD de 512 Go. Écran Liquid Retina XDR avec ProMotion jusqu’à 120 Hz, connectique Thunderbolt 5 et macOS Sequoia.",
    specifications: [
      { name: "Puce", value: "Apple M4 Pro, CPU 12 cœurs et GPU 16 cœurs", group: "Performance" },
      { name: "Neural Engine", value: "16 cœurs", group: "Performance" },
      { name: "Mémoire", value: "24 Go unifiée", group: "Performance" },
      { name: "Stockage", value: "SSD 512 Go", group: "Stockage" },
      { name: "Écran", value: "14,2 pouces Liquid Retina XDR, ProMotion 120 Hz", group: "Affichage" },
      { name: "Connectique", value: "Thunderbolt 5, USB-C, HDMI, MagSafe 3 et SDXC", group: "Connectique" },
      { name: "Système", value: "macOS Sequoia", group: "Logiciel" },
    ],
  },
  {
    id: "fallback-dell-latitude-3300",
    slug: "dell-latitude-3300-i5-8-go-256-go",
    name: "Latitude 3300",
    brand: "Dell",
    price: 180000,
    priceIsEstimate: true,
    image: "https://www.multivu.com/players/English/8356753-dell-technologies-bett-education/image/Latitude3300_1548180874597-HR.jpg",
    galleryImages: [
      "https://www.laptoparena.net/images/DELL_Latitude_3300_80TJM_image_2.jpg",
      "https://www.laptoparena.net/images/DELL_Latitude_3300_80TJM_image_3.jpg",
      "https://www.laptoparena.net/images/DELL_Latitude_3300_80TJM_image_4.jpg",
      "https://www.laptoparena.net/images/DELL_Latitude_3300_80TJM_image_5.jpg",
      "https://www.laptoparena.net/images/DELL_Latitude_3300_80TJM_image_6.jpg",
    ],
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i5 8e génération · 8 Go DDR4 · SSD 256 Go · Écran 13,3 pouces",
    description: "Dell Latitude 3300 compact avec Intel Core i5 de 8e génération, 8 Go de RAM DDR4 et SSD de 256 Go. Écran de 13,3 pouces, webcam intégrée, Wi-Fi, HDMI, USB-C et autonomie annoncée d’environ quatre heures.",
    specifications: [
      { name: "Processeur", value: "Intel Core i5, 8e génération", group: "Performance" },
      { name: "Mémoire", value: "8 Go DDR4", group: "Performance" },
      { name: "Stockage", value: "SSD 256 Go", group: "Stockage" },
      { name: "Écran", value: "13,3 pouces", group: "Affichage" },
      { name: "Connectique", value: "Wi-Fi, HDMI, USB-C, USB et webcam", group: "Connectique" },
      { name: "Autonomie", value: "Environ 4 heures annoncées", group: "Batterie" },
    ],
  },
  {
    id: "fallback-macbook-pro-16-m2-pro-2023",
    slug: "apple-macbook-pro-16-2023-m2-pro-32-go-1-to",
    name: "MacBook Pro 16 pouces M2 Pro (2023)",
    brand: "Apple",
    price: 1350000,
    image: "https://images.stockx.com/images/Apple-Macbook-Pro-16-M2-Pro-12-Core-CPU-38-Core-GPU-32GB-RAM-1TB-SSD-2023-Model-MNWA3LL-A-Space-Gray.jpg?auto=compress&bg=FFFFFF&dpr=2&fit=fill&fm=webp&h=500&q=90&trim=color&updated_at=1675359314&w=700",
    galleryImages: [
      "https://cleverbuy.imgbolt.de/media/d2/cb/66/1689866594/3_6b06fe981a64ce71.png",
      "https://www.tejar.pk/media/catalog/product/cache/3/image/9df78eab33525d08d6e5fb8d27136e95/a/p/apple_16-inch_macbook_pro_2023_9_-_tejar.jpg",
      "https://i.ebayimg.com/images/g/p-4AAOSwhgNksGDB/s-l960.jpg",
      "https://www.tonerpartner.cz/userdata/products/1818/ah13199291-mnw83-sk-64f846299a702.jpg",
      "https://www.custommacbd.com/cdn/shop/products/mbp14-space-gray-gallery1-2023-Custom-Mac-BD_9531e733-d409-4c98-a089-d55574b30b54.jpg?v=1674223032",
    ],
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Puce M2 Pro · 32 Go mémoire unifiée · SSD 1 To · Écran Liquid Retina XDR 16,2 pouces",
    description: "MacBook Pro 16 pouces de 2023 équipé de la puce Apple M2 Pro, avec 32 Go de mémoire unifiée et SSD de 1 To. Écran Liquid Retina XDR de 16,2 pouces, Wi-Fi 6E, Bluetooth 5.3, Touch ID et connectique Thunderbolt 4, HDMI, MagSafe 3 et SDXC.",
    specifications: [
      { name: "Année", value: "2023", group: "Configuration" },
      { name: "Puce", value: "Apple M2 Pro", group: "Performance" },
      { name: "Mémoire", value: "32 Go unifiée", group: "Performance" },
      { name: "Stockage", value: "SSD 1 To", group: "Stockage" },
      { name: "Écran", value: "16,2 pouces Liquid Retina XDR, 3456 × 2234", group: "Affichage" },
      { name: "Connectique", value: "3 Thunderbolt 4, HDMI, MagSafe 3, SDXC et prise casque", group: "Connectique" },
      { name: "Réseau", value: "Wi-Fi 6E et Bluetooth 5.3", group: "Connectique" },
      { name: "Accessoires annoncés", value: "Facture, garantie, 12 mois de SAV, housse et souris sans fil", group: "Services" },
    ],
  },
  {
    id: "fallback-iphone-16-pro-max-256-white",
    slug: "apple-iphone-16-pro-max-256-go-sim-physique-blanc",
    name: "iPhone 16 Pro Max 256 Go",
    brand: "Apple",
    price: 510000,
    image: "https://syomastore.ru/wa-data/public/shop/products/64/15/1564/images/6047/6047.970.jpg",
    galleryImages: [
      "https://medias4.ubaldi.com/visuels/7816596/pr_IPHONE16PROM256WHT-da650458e6-43.jpg",
      "https://cdn.visaovip.com/img/prod/apple-iphone-16-pro-max-myw43lla-a3084-256gb-swap-grade-a-white-titanium-americano/57470/730627.jpg",
      "https://assets.getmobil.com/uploads/6a539aaf-755e-4d80-aec4-ef5543123506/getmobil-apple-iphone-16-pro-max-beyaz-titanyum-3--600w.webp?w=600",
      "https://iplatinum.ru/image/cache/catalog/iPhone%2016%20Pro%20Max/048353f62217a7fe7d5343c56ca01e2c-800x800.png",
      "https://kontakt.az/media/catalog/product/cache/f8158826193ba5faa8b862a9bd1eb9e9/t/m/tm-dg-sbp-1105-sm-2936_4_1_.png",
    ],
    inStock: true,
    featured: false,
    category: "Smartphones",
    categorySlug: "smartphones",
    shortDescription: "256 Go · Blanc · SIM physique · Version Canada · Batterie 92 %",
    description: "iPhone 16 Pro Max blanc avec 256 Go de stockage, SIM physique et version Canada. État de batterie annoncé : 92 %. Les images de la galerie illustrent le modèle et ne représentent pas nécessairement l’appareil vendu.",
    specifications: [
      { name: "Stockage", value: "256 Go", group: "Configuration" },
      { name: "Couleur", value: "Blanc", group: "Configuration" },
      { name: "SIM", value: "SIM physique", group: "Réseau" },
      { name: "Version", value: "Canada", group: "Réseau" },
      { name: "État de batterie", value: "92 %", group: "État" },
    ],
  },
  {
    id: "fallback-iphone-16-pro-black",
    slug: "apple-iphone-16-pro-noir",
    name: "iPhone 16 Pro",
    brand: "Apple",
    price: 415000,
    image: "https://ibrat.ru/upload/iblock/cd2/2f9om89lpljw1l77x7fsg85div8fxbry.png",
    galleryImages: [
      "https://samazon.ae/cdn/shop/files/AppleiPhone16Pro128GBBlack_Sidra_al_muntaha_electronic_trading_llc_samazon.ae.jpg?v=1745427371",
      "https://astore.org.ua/image/cache/catalog/photo/2024-09/apple-iphone-16-pro-256gb-black-titanium-0-700x700.png",
      "https://avatars.mds.yandex.net/get-mpic/5255974/2a000001920ffaf5194abc14ad3109fabfb7/orig",
      "https://idrop.com.ua/image/cache/catalog/image/catalog/26.04.2024/phone/1022-700x700.jpg",
      "https://g-store.com.ua/image/cache/catalog/productfoto/12784/apple-iphone-16-pro-128gb-black-titanium-8-1200x1200.jpg",
    ],
    inStock: true,
    featured: false,
    category: "Smartphones",
    categorySlug: "smartphones",
    shortDescription: "Noir · Batterie 100 %",
    description: "iPhone 16 Pro noir. État de batterie annoncé : 100 %. La capacité de stockage et le type de SIM n’étaient pas précisés dans les informations reçues. Les images de la galerie illustrent le modèle et ne représentent pas nécessairement l’appareil vendu.",
    specifications: [
      { name: "Couleur", value: "Noir", group: "Configuration" },
      { name: "État de batterie", value: "100 %", group: "État" },
    ],
  },
  {
    id: "fallback-iphone-16-128",
    slug: "apple-iphone-16-128-go-sim-physique",
    name: "iPhone 16 128 Go",
    brand: "Apple",
    price: 335000,
    image: "https://platinum-jo.com/photos/6244.png",
    galleryImages: [
      "https://storage.micromagma.ma/micromagma/a2809354-68c4-47c6-b1c8-90b205a8883e.png",
      "https://assets.coverd.co/images/insurance/iphone16/iphone-16--1280w.48740d48.png",
      "https://images.kaina24.lt/43/43/apple-iphone-16-128gb-10.jpg",
      "https://cdn.lesnumeriques.com/optim/product/74/74130/1f30fcd8-iphone-16__450_400.jpg",
      "https://laboutique.orange.ci/sites/default/files/public/2025-05/apple-iphone-16-1%281%29.png",
    ],
    inStock: true,
    featured: false,
    category: "Smartphones",
    categorySlug: "smartphones",
    shortDescription: "128 Go · SIM physique · Version Canada",
    description: "iPhone 16 avec 128 Go de stockage, SIM physique et version Canada. La couleur et l’état de batterie n’étaient pas précisés dans les informations reçues. Les images de la galerie illustrent le modèle et ne représentent pas nécessairement l’appareil vendu.",
    specifications: [
      { name: "Stockage", value: "128 Go", group: "Configuration" },
      { name: "SIM", value: "SIM physique", group: "Réseau" },
      { name: "Version", value: "Canada", group: "Réseau" },
    ],
  },
  {
    id: "fallback-iphone-15-pro-128-cracked",
    slug: "apple-iphone-15-pro-128-go-sim-physique-fissure",
    name: "iPhone 15 Pro 128 Go",
    brand: "Apple",
    price: 315000,
    image: "https://i-system.gr/storage/i3commerce/images/i/p/iphone_pro_ti_img_04.jpg",
    galleryImages: [
      "https://d1likr6vgtxkkw.cloudfront.net/Custom/Content/Products/15/83/15836_apple-iphone-15-pro-128gb-titanio-natural_z3_638472196725896874.png",
      "https://media-cdn.bnn.in.th/332526/iPhone_15_Pro_Natural_Titanium_5-square_medium.jpg",
      "https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/300789_5_trglse.png",
      "https://cdn.asaxiy.uz/asaxiy-content/product/items/desktop/5751ec3e9a4feab575962e78e006250d2023092315141339805ZzWfkPMMFW.png.webp",
      "https://bestcomputerhub.com/wp-content/uploads/2024/08/iphone-15-pro-natural-titanium-002.webp",
    ],
    inStock: true,
    featured: false,
    category: "Smartphones",
    categorySlug: "smartphones",
    shortDescription: "128 Go · SIM physique · Version Canada · Batterie 81 % · Légère fissure arrière en haut",
    description: "iPhone 15 Pro avec 128 Go de stockage, SIM physique et version Canada. État de batterie annoncé : 81 %. L’appareil présente une légère fissure à l’arrière, dans la partie supérieure. Les images de la galerie illustrent le modèle et ne montrent pas la fissure de cet appareil.",
    specifications: [
      { name: "Stockage", value: "128 Go", group: "Configuration" },
      { name: "SIM", value: "SIM physique", group: "Réseau" },
      { name: "Version", value: "Canada", group: "Réseau" },
      { name: "État de batterie", value: "81 %", group: "État" },
      { name: "État extérieur", value: "Légère fissure à l’arrière, en haut", group: "État" },
    ],
  },
  {
    id: "fallback-dell-latitude-5580-satan-2",
    slug: "dell-latitude-5580-satan-2-i7-16-go-512-go-ssd",
    name: "Dell Latitude 5580 Workstation « Satan 2 »",
    brand: "Dell",
    price: 200000,
    image: "https://static.webx.pk/files/78721/Images/5580-1-78721-2208201-230924104748300.jpg",
    galleryImages: [
      "https://tpc-store.com/wp-content/uploads/2024/05/1-242.webp",
      "https://www.laptopid.ee/images/product/584/3460/medium.png?_=77497150",
      "https://compbest.com.ua/content/images/33/noutbuk_dell_latitude_5580_15.6_1920x1080_ips_intel_core_i5-6300u_2_4_yadra_po_2.4_-_3.0_ghz_16_gb_ddr4_256_gb_ssd_intel_hd_graphics_520_touchid_sim-15726317369325_small11.png",
      "https://i.ebayimg.com/images/g/3ckAAeSwN4RpVXcl/s-l1600.jpg",
      "https://item-shopping.c.yimg.jp/i/n/genel_n-dell-5580-i7_1_d_20240217212516",
    ],
    inStock: true,
    featured: false,
    category: "Ordinateurs portables",
    categorySlug: "ordinateurs-portables",
    shortDescription: "Core i7-7600U · 16 Go DDR4 · SSD 512 Go · NVIDIA annoncée · 200 000 FCFA",
    description: "Dell Latitude 5580, surnommé « Satan 2 » dans l’annonce, proposé à 200 000 FCFA. Configuration annoncée : Intel Core i7-7600U à 2,80 GHz, 16 Go de RAM DDR4 et SSD de 512 Go. L’annonce cite à la fois une NVIDIA GeForce 940MX et une GeForce 950MX : la carte réellement installée est à confirmer. Dell documente une GeForce 940MX parmi les options du Latitude 5580 et indique un maximum officiel de 32 Go de mémoire; l’extension à 64 Go annoncée par le vendeur n’est donc pas reprise comme caractéristique garantie. Clavier rétroéclairé, écran 15,6 pouces, lecteur d’empreintes, USB-C et HDMI annoncés. Les logiciels de CAO/Adobe et jeux cités dépendent des exigences du programme et du GPU effectivement installé; leur compatibilité ou leurs performances ne sont pas garanties par cette fiche. Les images de la galerie illustrent le modèle, elles ne montrent pas nécessairement l’appareil vendu.",
    specifications: [
      { name: "Processeur", value: "Intel Core i7-7600U, 2,80 GHz annoncés", group: "Performance" },
      { name: "Mémoire", value: "16 Go DDR4 PC4", group: "Performance" },
      { name: "Mémoire maximale", value: "32 Go selon les spécifications Dell; extension à 64 Go annoncée à confirmer", group: "Performance" },
      { name: "Stockage", value: "SSD 512 Go", group: "Stockage" },
      { name: "Carte graphique", value: "NVIDIA GeForce 940MX 2 Go GDDR5 annoncée; la fiche source mentionne aussi une 950MX, référence à confirmer", group: "Affichage" },
      { name: "Écran", value: "15,6 pouces", group: "Affichage" },
      { name: "Clavier", value: "Rétroéclairé", group: "Conception" },
      { name: "Sécurité", value: "Lecteur d’empreintes annoncé", group: "Connectique" },
      { name: "Ports", value: "USB-C et HDMI annoncés; cinq ports USB indiqués dans l’annonce, nombre à vérifier sur l’appareil", group: "Connectique" },
      { name: "Prix", value: "200 000 FCFA", group: "Prix" },
    ],
  },
];

export function getFallbackProducts(options: { categorySlug?: string; featured?: boolean; take?: number } = {}) {
  const products = fallbackCatalogue.filter((product) =>
    (!options.categorySlug || product.categorySlug === options.categorySlug) &&
    (!options.featured || product.featured),
  );
  return options.take ? products.slice(0, options.take) : products;
}

export function getFallbackProductBySlug(slug: string) {
  const product = fallbackCatalogue.find((item) => item.slug === slug);
  if (!product) return null;
  return {
    ...product,
    stockQuantity: 1,
    sku: "",
    images: [product.image, ...(product.galleryImages || [])],
  };
}
