import type { Metadata } from "next";
import { CircleAlert, Tags } from "lucide-react";
import { createBrand, createCategory, updateBrand, updateCategory } from "@/app/admin/actions";
import { getAdminCatalogue } from "@/lib/admin-data";

export const metadata: Metadata = { title: "Marques & catégories | Administration Zink Tech", robots: { index: false, follow: false } };
const fieldClass = "h-10 w-full rounded-lg border border-[#dfe4ed] bg-white px-3 text-xs text-[#34415a] outline-none focus:border-[#2872bf] focus:ring-4 focus:ring-[#2872bf]/10";
type Props = { searchParams: Promise<{ cree?: string; misajour?: string }> };

export default async function AdminCataloguePage({ searchParams }: Props) {
  const [data, query] = await Promise.all([getAdminCatalogue(), searchParams]);
  return <div>
    <div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#2872bf]">ORGANISATION</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] text-[#142451]">Marques & catégories</h1><p className="mt-2 text-sm text-[#737e91]">Structurez le catalogue que les clients parcourent.</p></div>
    {!data.connected && <div className="mt-6 flex gap-3 rounded-xl border border-[#f0d99b] bg-[#fff8e4] p-4 text-sm leading-6 text-[#715418]"><CircleAlert size={18} className="mt-0.5 shrink-0"/><p>Connectez PostgreSQL pour gérer les marques et catégories réelles.</p></div>}
    {query.cree && <p role="status" className="mt-4 rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-800">L’élément a été ajouté au catalogue.</p>}
    {query.misajour && <p role="status" className="mt-4 rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-800">Les changements ont été enregistrés.</p>}
    <div className="mt-6 grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl border border-[#e7eaf0] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Marques</h2><p className="mt-1 text-xs text-[#8993a3]">{data.connected ? `${data.brands.length} marque(s)` : "Données non chargées"}</p></div><Tags size={18} className="text-[#7188aa]"/></div>
        <div className="mt-4 space-y-2">{data.brands.map((brand) => <form action={updateBrand} key={brand.id} className="rounded-xl border border-[#edf0f4] p-3"><input type="hidden" name="id" value={brand.id}/><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input className={fieldClass} name="name" aria-label="Nom de la marque" defaultValue={brand.name} required/><input className={fieldClass} name="slug" aria-label="Adresse de la marque" defaultValue={brand.slug} required/><button className="h-10 rounded-lg border border-[#dfe4ed] px-3 text-[10px] font-semibold text-[#536078] hover:bg-[#f7f9fc]">Enregistrer</button></div><div className="mt-2 flex items-center gap-2"><input className={fieldClass} name="description" aria-label="Description de la marque" defaultValue={brand.description} placeholder="Description"/><span className="shrink-0 text-[10px] text-[#8b94a3]">{brand.products} produit(s)</span></div></form>)}</div>
        <form action={createBrand} className="mt-5 border-t border-[#edf0f4] pt-5"><h3 className="text-xs font-semibold text-[#47546b]">Ajouter une marque</h3><div className="mt-3 grid gap-2 sm:grid-cols-2"><input className={fieldClass} name="name" aria-label="Nouvelle marque" placeholder="Nom" required disabled={!data.connected}/><input className={fieldClass} name="slug" aria-label="Adresse" placeholder="Adresse (optionnelle)"/></div><input className={`${fieldClass} mt-2`} name="description" placeholder="Description (optionnelle)"/><button disabled={!data.connected} className="mt-3 h-9 rounded-lg bg-[#173986] px-4 text-xs font-semibold text-white hover:bg-[#10245d] disabled:opacity-50">Ajouter la marque</button></form>
      </section>
      <section className="rounded-2xl border border-[#e7eaf0] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Catégories</h2><p className="mt-1 text-xs text-[#8993a3]">{data.connected ? `${data.categories.length} catégorie(s)` : "Données non chargées"}</p></div><Tags size={18} className="text-[#7188aa]"/></div>
        <div className="mt-4 space-y-2">{data.categories.map((category) => <form action={updateCategory} key={category.id} className="rounded-xl border border-[#edf0f4] p-3"><input type="hidden" name="id" value={category.id}/><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input className={fieldClass} name="name" aria-label="Nom de la catégorie" defaultValue={category.name} required/><input className={fieldClass} name="slug" aria-label="Adresse de la catégorie" defaultValue={category.slug} required/><button className="h-10 rounded-lg border border-[#dfe4ed] px-3 text-[10px] font-semibold text-[#536078] hover:bg-[#f7f9fc]">Enregistrer</button></div><div className="mt-2 flex items-center gap-2"><input className={fieldClass} name="description" aria-label="Description de la catégorie" defaultValue={category.description} placeholder="Description"/><span className="shrink-0 text-[10px] text-[#8b94a3]">{category.products} produit(s)</span></div></form>)}</div>
        <form action={createCategory} className="mt-5 border-t border-[#edf0f4] pt-5"><h3 className="text-xs font-semibold text-[#47546b]">Ajouter une catégorie</h3><div className="mt-3 grid gap-2 sm:grid-cols-2"><input className={fieldClass} name="name" aria-label="Nouvelle catégorie" placeholder="Nom" required disabled={!data.connected}/><input className={fieldClass} name="slug" aria-label="Adresse" placeholder="Adresse (optionnelle)"/></div><input className={`${fieldClass} mt-2`} name="description" placeholder="Description (optionnelle)"/><button disabled={!data.connected} className="mt-3 h-9 rounded-lg bg-[#173986] px-4 text-xs font-semibold text-white hover:bg-[#10245d] disabled:opacity-50">Ajouter la catégorie</button></form>
      </section>
    </div>
  </div>;
}
